### PR TITLE
Twelve: Add audio format information

### PR DESCRIPTION
**Pull request by SebaUbuntu**

### CODE REVIEW

**Comment by luca020400** [comment]
Can make it shown in a dialog (bottom) on file type click?

**Comment by luca020400** [comment]
fyi some stuff gets disabled in float case ex playback speed
We probably need to query available COMMANDS and show UI elements based on that

**Comment by SebaUbuntu** [comment]
> fyi some stuff gets disabled in float case ex playback speed We probably need to query available COMMANDS and show UI elements based on that

Platform playback parameters fixes that

**Comment by SebaUbuntu** [comment]
gtg for me

**Review by luca020400 — APPROVED** [review]

**Pull request merged**
