### PR TITLE
Twelve: Make UniqueModel a plain interface

### PR DESCRIPTION
**Pull request by luca020400**

### CODE REVIEW

**Comment by luca020400** [comment]
I don't know how I feel about it, there maybe other places to replace.

**Comment by luca020400** [comment]
Codegen is far worse.

**Comment by SebaUbuntu** [comment]
By any chance, since the interface is now sealed, can we remove `<*>` from UniqueItem references anyway?

**Comment by luca020400** [comment]
You can, I think I got them all, there weren't many

**Comment by luca020400** [comment]
Still not worth it, it generates +100 asm (600 -> 700) instructions per model :(

**Pull request closed without merging**
