### PR TITLE
Twelve: Poll current position every 200ms

### PR DESCRIPTION
**Pull request by luca020400**
Note:
I didn't create a different flow because we must ensure
we pull the position only after the playback status
is valid otherwise the slider will have invalid data.

### CODE REVIEW

**Comment by luca020400** [comment]
@SebaUbuntu a split flow might be problematic because of the async.
Since the 2 flows run of different threads the currentPosition might be delivered before we setup the UI.
Usually this is only a problem on the first play of a song, but this is extra cautions and ensure we send paired data

**Comment by luca020400** [comment]
Also, the 200ms comes from the progress bar UI module of media3, I didn't made it up

**Comment by luca020400** [comment]
nvm that isn't enough, we must ensure each current position is of the corresponding status

**Comment by luca020400** [comment]
~~This seems to work?~~

**Comment by SebaUbuntu** [comment]
Just borrowed `PlayerControlView.java` code, works fine

**Pull request merged**
